environment: default
imgix:
  header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
  header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
  header_gif: "?ch=Width,Save-Data&fm=gif"
  jpg: "?fm=jpg&auto=format&lossless=true"
  png: "?fm=png&auto=format&lossless=1"
  gif: ""
code_languages:
  - display_name: Python
    key: python
  - display_name: Ruby
    key: ruby
  - display_name: Curl
    key: bash
footer_scripts:
  - snowplow: false
  - marketo: false
  - adroll: false

algolia:
  appId: EOIG7V0A2O
  apiKey: c7ec32b3838892b10610af30d06a4e42
  indexName: docsearch_docs_prod

datadog:
  clientToken: pub16bb5ef3e9bf55f156338987e27246c7
  forwardErrorsToLogs: false