site_name: "Datadog Infrastructure and Application Monitoring"
meta_image: datadog_logo_share_tt.png
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "このページの日本語版はまだありません。現在翻訳中です。<br> 現在の翻訳プロジェクト に対するご質問またはフィードバックがございましたら、ぜひ<a href=\"https://docs.datadoghq.com/fr/help/\">こちら</a>までお知らせください。"
announcement_banner:
  text: "Join us at the Dash conference! July 16-17, NYC"
  link: "https://www.dashcon.io/?utm_source=Trade+Show&utm_medium=DatadogOrganized&utm_campaign=Tradeshow-201907DashBanner"
  exclude: []
