site_name: Datadogでインフラストラクチャーとアプリケーションのモニタリング
meta_image: datadog_logo_share_tt.png
meta_title: Datadogを始めてみましょう
meta_description: Datadogが大規模なクラウドのモニタリングサービスをリードします。
disclaimer: このページは英語では対応しておりません。随時翻訳に取り組んでいます。翻訳に関してご質問やご意見ございましたら、お気軽にご連絡ください。
announcement_banner:
  desktop_message: "<span class='d-inline'>日本初となるDatadog Summit を11月13日水曜日に東京 明治記念館にて開催いたします。</span><span class='d-none d-lg-inline'>是非ご参加ください！</span>"
  mobile_message: Datadog Summit Tokyo 開催！
  link: 'https://www.datadoghq.com/summit/tokyo19/'
  exclude: []
