environment: default
imgix:
  header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
  header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
  header_gif: "?ch=Width,Save-Data&fm=gif"
  jpg: "?fm=jpg&auto=format&lossless=true"
  png: "?fm=png&auto=format&lossless=1"
  gif: ""
announcement_banner:
  text: "Join us at the Dash conference! July 16-17, NYC"
  link: "https://www.dashcon.io/?utm_source=Trade+Show&utm_medium=DatadogOrganized&utm_campaign=Tradeshow-201907DashBanner"
  exclude: []
code_languages:
  - display_name: Python
    key: python
  - display_name: Ruby
    key: ruby
  - display_name: Curl
    key: bash
footer_scripts:
  - snowplow: false
  - marketo: false
  - adroll: false

