Agent:
- content/en/agent/**/*

API:
- content/en/api/**/*

"Cloud Functions":
- content/en/graphing/infrastructure/serverless.md

Developers:
- content/en/developers/**/*

Integration:
- content/en/getting_started/integrations/**/*
- content/en/integrations/**/*

Logs:
- content/en/logs/**/*

Monitors:
- content/en/monitors/**/*

"Network Performance Monitoring":
- content/en/network_performance_monitoring/**/*

RUM:
- content/en/real_user_monitoring/**/*

Synthetics:
- content/en/api/synthetics/**/*

Tracing:
- content/en/tracing/**/*
