title: "Docs"
baseURL: "http://localhost:1313/"
metadataformat: "yaml"

pygmentsuseclasses: true

# taxonomies
taxonomies:
  tag: "tags"
  video: "videos"
  example: "examples"
preserveTaxonomyNames: true

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    #languageName: "English"
    #languageCode: "en-US"
    weight: 0
    menu:
      main_references:
        - identifier: menu_references_api
          name: "API"
          url: "/api/"
          weight: 10
        - identifier: menu_references_tracing
          name: "Tracing"
          url: "/tracing/"
          weight: 20
        - identifier: menu_references_libraries
          name: ""
          url: "/libraries/"
          weight: 30
        - identifier: menu_references_monitoring
          name: ""
          url: "/monitoring/"
          weight: 40
        - identifier: menu_references_graphing
          name: ""
          url: "/graphing/"
          weight: 50
        - identifier: menu_references_host_names
          name: ""
          url: "/hostnames/"
          weight: 60
        - identifier: menu_references_integrations
          name: ""
          url: "/integrations/"
          weight: 70
        - identifier: menu_references_dogstatsd
          name: ""
          url: "/guides/dogstatsd/"
          weight: 80
        - identifier: menu_references_examples
          name: ""
          url: "/examples/"
          weight: 90
        - identifier: menu_references_videos
          name: ""
          url: "/videos/"
          weight: 100
        - identifier: menu_references_billing
          name: ""
          url: "/guides/billing/"
          weight: 110
        - identifier: menu_references_faq
          name: ""
          url: "/faq/"
          weight: 120
      basic_agent:
        - identifier: amazonlinux
          name: ""
          url: /guides/basic_agent_usage/amazonlinux/
          weight: 100

        - identifier: centos
          name: ""
          url: /guides/basic_agent_usage/centos/
          weight: 100

        - identifier: docker
          name: ""
          url: /guides/basic_agent_usage/docker/
          weight: 100

        - identifier: deb
          name: ""
          url: /guides/basic_agent_usage/deb/
          weight: 100

        - identifier: fedora
          name: ""
          url: /guides/basic_agent_usage/fedora/
          weight: 100

        - identifier: osx
          name: ""
          url: /guides/basic_agent_usage/osx/
          weight: 100

        - identifier: redhat
          name: ""
          url: /guides/basic_agent_usage/redhat/
          weight: 100

        - identifier: ubuntu
          name: ""
          url: /guides/basic_agent_usage/ubuntu/
          weight: 100

        - identifier: windows
          name: ""
          url: /guides/basic_agent_usage/windows/
          weight: 100

        - identifier: source
          name: ""
          url: /guides/basic_agent_usage/source/
          weight: 100

  ja:
    #languagename: "日本語"
    weight: 1
    menu:
      main_references:
        - identifier: menu_references_api
          name: "API"
          url: "/api/"
          weight: 10
        - identifier: menu_references_tracing
          name: "Tracing"
          url: "/tracing/"
          weight: 20
        - identifier: menu_references_libraries
          name: ""
          url: "/libraries/"
          weight: 30
        - identifier: menu_references_monitoring
          name: ""
          url: "/monitoring/"
          weight: 40
        - identifier: menu_references_graphing
          name: ""
          url: "/graphing/"
          weight: 50
        - identifier: menu_references_host_names
          name: ""
          url: "/hostnames/"
          weight: 60
        - identifier: menu_references_integrations
          name: ""
          url: "/integrations/"
          weight: 70
        - identifier: menu_references_dogstatsd
          name: ""
          url: "/guides/dogstatsd/"
          weight: 80
        - identifier: menu_references_examples
          name: ""
          url: "/examples/"
          weight: 90
        - identifier: menu_references_videos
          name: ""
          url: "/videos/"
          weight: 100
        - identifier: menu_references_billing
          name: ""
          url: "/guides/billing/"
          weight: 110
        - identifier: menu_references_faq
          name: ""
          url: "/faq/"
          weight: 120

params:
  img_url: "http://localhost:1313/"
  imgix:
    header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
    header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
    header_gif: "?ch=Width,Save-Data&fm=gif"
    jpg: "?fm=jpg&auto=format&lossless=true"
    png: "?fm=png&auto=format&lossless=1"
    gif: ""
  static_url: "http://localhost:1313/"
  code_languages:
    - Python
    - Ruby
    - Console
  footer_scripts:
    - snowplow: false
    - marketo: false
    - adroll: false
