environment: live
img_url: "https://datadog-docs.imgix.net/"
static_url: "https://docs.datadoghq.com/"
ga: UA-21102638-5

header_scripts:
  - hotjar: true
  - google-site-tag: true
  - google-tag-manager: true
  - marketo: true

footer_scripts:
  - snowplow: true
  - adroll: true

hotjar:
  id: 1021060

algolia:
  appId: EOIG7V0A2O
  apiKey: c7ec32b3838892b10610af30d06a4e42
  indexName: docsearch_docs_prod
