environment: live
img_url: "https://datadog-docs.imgix.net/"
static_url: "https://docs.datadoghq.com/"
footer_scripts:
- snowplow: true
- marketo: true
- adroll: true

datadog:
  clientToken: pub16bb5ef3e9bf55f156338987e27246c7
  applicationId: 3493b4e7-ab12-4852-8836-ba96af7bc745
  logging_handler: http
