environment: preview
img_url: "https://datadog-docs.imgix.net/"
static_url: "https://docs-staging.datadoghq.com/"

datadog:
  clientToken: pub36877d3864fab670b5ae7e1d5d26cb08
  applicationId: c4e83ad8-4eda-4d2e-aae1-d943abce0463
  forwardErrorsToLogs: true
