environment: preview
img_url: "https://datadog-docs-staging.imgix.net/"
static_url: "https://docs-staging.datadoghq.com/"
ga: UA-21102638-9

header_scripts:
  - hotjar: true
  - google-site-tag: false
  - google-tag-manager: false
  - marketo: false

footer_scripts:
  - snowplow: false
  - adroll: false

hotjar:
  id: 1022108

algolia:
  appId: EOIG7V0A2O
  apiKey: c7ec32b3838892b10610af30d06a4e42
  indexName: docsearch_docs_preview
