---
baseURL: https://dmin7ss6aif3e.cloudfront.net/
buildfuture: false
builddrafts: false
params:
  environment: live
  img_url: "https://dmin7ss6aif3e.cloudfront.net/"
  static_url: "https://dmin7ss6aif3e.cloudfront.net/"
