---
baseURL: https://docs-staging.datadoghq.com/
buildfuture: false
builddrafts: false
params:
  environment: live
  img_url: "https://docs-staging.datadoghq.com/"
  static_url: "https://docs-staging.datadoghq.com/"
