---
- org_name: DataDog
  
  repos:
  - repo_name: dogweb
    
    contents:

    - content_name: source
      branch: prod
      globs:
      - dd/utils/context/source.py
      path_to_remove: ''
      dest_dir: ''

    - content_name: integrations
      branch: prod
      globs:
      - integration/**/*_metadata.csv
      - integration/**/manifest.json
      - integration/**/service_checks.json
      - integration/**/README.md
      path_to_remove: ''
      dest_dir: ''

  - repo_name: integrations-core
    contents:

    - content_name: integrations
      branch: master
      globs:
      - "*[!}]/metadata.csv"
      - "*[!}]/manifest.json"
      - "*[!}]/service_checks.json"
      - "*[!}]/README.md"
      dest_dir: ''
      path_to_remove: ''

    - content_name: integrations-core-doc
      branch: master
      globs:
      - docs/**
      dest_dir: ''
      path_to_remove: ''

  - repo_name: integrations-extras
    contents:

    - content_name: integrations
      branch: master
      globs:
      - "**/metadata.csv"
      - "**/manifest.json"
      - "**/service_checks.json"
      - "**/README.md"
      path_to_remove: ''
      dest_dir: ''
